---
fail_fast: false
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: trailing-whitespace
        exclude: |
          (?x)(
              \.bpa$|
              \.bpaspin$|
              \.cube$|
              \.in$|
              \.inp$|
              \.molden$|
              \.out$|
              ^data/ADF|
              ^data/DALTON|
              ^data/FChk|
              ^data/GAMESS|
              ^data/Gaussian|
              ^data/Jaguar|
              ^data/Molcas|
              ^data/Molpro|
              ^data/MOPAC|
              ^data/NBO|
              ^data/NWChem|
              ^data/ORCA|
              ^data/Psi4|
              ^data/QChem|
              ^data/regression|
              ^data/Turbomole|
              ^data/XTB
          )
      - id: end-of-file-fixer
        exclude: |
          (?x)(
              \.bpa$|
              \.bpaspin$|
              \.cube$|
              \.in$|
              \.inp$|
              \.molden$|
              \.out$|
              ^data/ADF|
              ^data/DALTON|
              ^data/FChk|
              ^data/GAMESS|
              ^data/Gaussian|
              ^data/Jaguar|
              ^data/Molcas|
              ^data/Molpro|
              ^data/MOPAC|
              ^data/NBO|
              ^data/NWChem|
              ^data/ORCA|
              ^data/Psi4|
              ^data/QChem|
              ^data/regression|
              ^data/Turbomole|
              ^data/XTB
          )
      - id: fix-byte-order-marker
        exclude: |
          (?x)(
              \.bpa$|
              \.bpaspin$|
              \.cube$|
              \.in$|
              \.inp$|
              \.molden$|
              \.out$|
              ^data/ADF|
              ^data/DALTON|
              ^data/FChk|
              ^data/GAMESS|
              ^data/Gaussian|
              ^data/Jaguar|
              ^data/Molcas|
              ^data/Molpro|
              ^data/MOPAC|
              ^data/NBO|
              ^data/NWChem|
              ^data/ORCA|
              ^data/Psi4|
              ^data/QChem|
              ^data/regression|
              ^data/Turbomole|
              ^data/XTB
          )
      - id: mixed-line-ending
        exclude: |
          (?x)(
              \.bpa$|
              \.bpaspn$|
              \.cube$|
              \.in$|
              \.inp$|
              \.molden$|
              \.out$|
              ^data/ADF|
              ^data/DALTON|
              ^data/FChk|
              ^data/GAMESS|
              ^data/Gaussian|
              ^data/Jaguar|
              ^data/Molcas|
              ^data/Molpro|
              ^data/MOPAC|
              ^data/NBO|
              ^data/NWChem|
              ^data/ORCA|
              ^data/Psi4|
              ^data/QChem|
              ^data/regression|
              ^data/Turbomole|
              ^data/XTB
          )
      - id: check-merge-conflict
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]
  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: "v1.7.3.17"
    hooks:
      - id: actionlint
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]
  - repo: https://github.com/PyCQA/isort
    rev: "5.13.2"
    hooks:
      - id: isort
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: "v1.3.0"
  #   hooks:
  #     - id: mypy
  #       additional_dependencies:
  #         - numpy
  #         - packaging
  #         - pandas-stubs
  #         # - scipy
  #         - types-setuptools
  #       args: []
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        files: \.py$
        args:
          - --license-filepath
          - .github/license_header.txt
          - --use-current-year
          - --no-extra-eol
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
