language: python
python:
  - 2.7
  - 3.4
  - 3.7
addons:
    apt:
      packages:
        - swig
cache:
  pip: true

before_install:
  - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu cosmic universe"
  - sudo apt update
  - sudo apt install libopenbabel-dev
  - pip install -r requirements.txt
  - pip install pytest-faulthandler

install:
  - pip install .

before_script:
  - |
    export DOCS_BRANCH_NAME=master
    export DOCS_REPO_NAME=cclib.github.io
    export DOCS_REPO_OWNER=cclib
    export DOCS_ROOT_DIR="${TRAVIS_BUILD_DIR}"/doc/sphinx
    export DOCS_BUILD_DIR="${DOCS_ROOT_DIR}"/_build/html
    export THEME_DIR="${DOCS_ROOT_DIR}"/_themes
  - install -dm755 "${THEME_DIR}"

script:
  - env | sort
  - bash travis/run_pytest.bash
  - bash travis/build_docs.bash

after_success:
  - |
    if [[ "${TRAVIS_BRANCH}" == master && "${TRAVIS_PULL_REQUEST}" == false && $TRAVIS_PYTHON_VERSION == 3.7 ]];
    then
        # Commits to master that are not pull requests, that is, only actual
        # addition of code to master, should deploy the documentation.
        bash ${TRAVIS_BUILD_DIR}/travis/deploy_docs_travis.bash
    fi
