---
name: ci

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

concurrency:
  group: ci-${{github.ref}}-${{github.event.pull_request.number || github.run_number}}
  cancel-in-progress: true

jobs:
  nix:
    uses: ./.github/workflows/nix.yml
  unit-tests:
    uses: ./.github/workflows/test_and_package.yml
  docs:
    uses: ./.github/workflows/docs.yml
    secrets: inherit
  publish:
    needs: [nix, unit-tests, docs]
    uses: ./.github/workflows/publish.yml
  all:
    needs: [unit-tests, publish]
    runs-on: ubuntu-22.04
    steps:
      - name: Success
        run: "true"
